modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Axieum/AuthMe/issues"

[[mods]]
modId="authme"
version="${file.jarVersion}"
displayName="Auth Me"
displayURL="https://github.com/Axieum/AuthMe"
logoFile="logo.png"
credits="TechnicianLP"
authors="Axieum"
description='''
Authenticate yourself in Minecraft and re-validate your session.
'''

[[dependencies.authme]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.16)"
    ordering="NONE"
    side="CLIENT"
